version: '3.4'

services:
  api:
    build:
      context: stubs
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:8080"
    volumes:
      - ./stubs:/stubs
    command: -p 8080 --middlewares randomize.js --watch db.js    
    environment:
      - FAILURE_RATE=0.1
      - MIN_DELAY_MS=0
      - MAX_DELAY_MS=3000

  app:
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "4000:80"
